### PR TITLE
optimize tito widget remaining tickets badge positioning

### PR DESCRIPTION
**Pull request by manpenaloza**
pr optimizes the positioning of the remaining tickets badge of the tito widget.
now more straight, more clear, more responsive.

nothing issue related, just thought that'd need optimization.

### CODE REVIEW

**Comment by bebraw** [comment]
Deploy preview for *react-finland* processing.

Built with commit 80ec815e5cbdbed8a62f4030ba47fde182e08a5e

https://app.netlify.com/sites/react-finland/deploys/5a8f10e148769b6b6dbe2bf3

**Comment by bebraw** [comment]
Can you rebase? I'll have a look after that.

**Comment by manpenaloza** [comment]
@bebraw done

**Comment by bebraw** [comment]
Nice one. 👍

**Pull request merged**
